Use V2 API
sitn/mobility_updater pull request #12
Opened 2024-05-14 07:13 UTC by kalbermattenm

This uses the new version of the API. Following changes were made:
* One can choose only to update the bike availability at each station use option `-s yes` (default `no`). This makes the scripts runtime faster. At SITN we are going to run the full update once a week and the fast update each 5 or 15 minutes.
* The base `provider_url` has disappeared from the API, thus the column was suppressed in the table creation as well.
* Be sure to update your `config.yml` file (see the example file)

@rbovard, could you review that?

ping @maltaesousa, @pfanguin

2024-05-14 12:03 UTC, rbovard requested changes
Thanks a lot for the upgrade, it's working fine.

FYI the data are not up to date, even in the new webservice (and in geoadmin)... In my area, the last update is from 29.04.2024.

I've added some little remarks in the code.

I think you can also update (or remove) the link in the readme to https://sharedmobility.ch/gbfs.json since it's not the one used anymore.

2024-05-15 12:53 UTC, rbovard approved these changes

2024-05-15 12:54 UTC, rbovard commented
LGTM, thanks!

2024-05-15 13:07 UTC, kalbermattenm commented
Thanks for the review!

2024-05-15 13:07 UTC, merged